---

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-07T23-21-09Z
    container_name: minio
    restart: always
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - $DIR_DATA/minio:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.entrypoints=http"
      - "traefik.http.routers.website.rule=Host(`minio.a3888s.pp.ua`)"
      - "traefik.http.routers.website-secure.entrypoints=https"
      - "traefik.http.routers.website-secure.rule=Host(`minio.a3888s.pp.ua`)"
      - "traefik.http.routers.website-secure.tls=true"
      - "traefik.http.routers.website-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.website-secure.tls.domains[0].main=a3888s.pp.ua"
      - "traefik.http.routers.website-secure.tls.domains[0].sans=*.a3888s.pp.ua"